server:
  port: 9090

spring:
  application:
    name: hello
  datasource:
    url: jdbc:postgresql://localhost:5432/hello-java
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # sql:
  #   init:
  #     mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQLDialect
    #     format_sql: true

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
